[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161e"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
size = 12.0

[font.bold]
family = "MonaspiceRn Nerd Font"
style = "Bold"

[font.italic]
family = "MonaspiceXe Nerd Font"
style = "Medium Italic"

[font.normal]
family = "MonaspiceNe Nerd Font"
style = "Medium"

# [[keyboard.bindings]]
# chars = "\u0017"
# key = "Back"
# mods = "Control"

# [[keyboard.bindings]]
# chars = "\u0000"
# key = "Space"
# mods = "Control"

[shell]
program = "wsl.exe ~ -d Ubuntu-22.04"

[window]
opacity = 0.95
title = "Aquila"
dynamic_title = false
padding = { x = 10, y=6}
dynamic_padding = true
decorations = "none"

[window.dimensions]
columns = 140
lines = 35

[window.position]
x = 50
y = 35

[selection]
save_to_clipboard = true